server:
  port: 8080

spring:
  application:
    name: api-gateway

app:
  mensaje:
    bienvenida: "Bienvenido al API Gateway - Sistema Mesa de Ayuda"

info:
  app:
    name: api-gateway
    description: Puerta de entrada unica del sistema Mesa de Ayuda
    version: 1.0.0