server:
  port: 8082

spring:
  application:
    name: ms-tickets
  datasource:
    url: jdbc:mysql://localhost:3306/tickets_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

app:
  mensaje:
    bienvenida: "Servicio de Tickets activo"

info:
  app:
    name: ms-tickets
    description: Servicio de gestion de tickets de soporte
    version: 1.0.0